// List of major German insurance companies
export const germanInsuranceCompanies = [
  "Allianz",
  "AXA",
  "ADAC Versicherung",
  "Barmenia",
  "Cosmos Direkt",
  "DA Direkt",
  "Debeka",
  "DEVK",
  "Die Bayerische",
  "ERGO",
  "Generali",
  "Gothaer",
  "HanseMerkur",
  "HDI",
  "Helvetia",
  "HUK-COBURG",
  "InterRisk",
  "LVM",
  "Nürnberger",
  "Provinzial",
  "R+V Versicherung",
  "Signal Iduna",
  "SV SparkassenVersicherung",
  "VGH",
  "VHV",
  "Württembergische",
  "WWK",
  "Zurich",
  "Keine bisherige Versicherung",
  "Sonstige",
]; 